const tagsBlock = [
  {title: 'Header', closed: false},
  {title: 'Footer', closed: false},
  {title: 'Section', closed: false},
  {title: 'Div', closed: false},
  {title: 'Paragraph', closed: false},
  {title: 'Address', closed: false},
  {title: 'Blockquote', closed: false},
  {title: 'Center', closed: false},
  {title: 'Fieldset', closed: false},
  {title: 'Article', closed: false},
  {title: 'Form', closed: false},
  {title: 'Details', closed: false},
  {title: 'dd', closed: false},
  {title: 'Dialogs', closed: false},
  {title: 'dt', closed: false},
  {title: 'dl', closed: false},
  {title: 'Figure', closed: false},
  {title: 'Hgroup', closed: false},
  {title: 'Nav', closed: false},
  {title: 'ol', closed: false},
  {title: 'ul', closed: false},
  {title: 'Table', closed: false},
  {title: 'Main', closed: false},
  {title: 'pre', closed: false},
  {title: 'hr', closed: true},
  {title: 'Figcaption', closed: false},
  {title: 'Aside', closed: false},
];

const tagsInline = [
  {title: 'b', closed: false},
  {title: 'Big', closed: false},
  {title: 'i', closed: false},
  {title: 'Small', closed: false},
  {title: 'tt', closed: false},
  {title: 'Abbr', closed: false},
  {title: 'Acronym', closed: false},
  {title: 'Cite', closed: false},
  {title: 'Code', closed: false},
  {title: 'dfn', closed: false},
  {title: 'em', closed: false},
  {title: 'kbd', closed: false},
  {title: 'Strong', closed: false},
  {title: 'Samp', closed: false},
  {title: 'Time', closed: false},
  {title: 'Var', closed: false},
  {title: 'a', closed: false},
  {title: 'bdo', closed: false},
  {title: 'br', closed: true},
  {title: 'img', closed: true},
  {title: 'Map', closed: false},
  {title: 'Object', closed: false},
  {title: 'q', closed: false},
  {title: 'Script', closed: false},
  {title: 'Span', closed: false},
  {title: 'Sub', closed: false},
  {title: 'Sup', closed: false},
  {title: 'Button', closed: false},
  {title: 'Input', closed: true},
  {title: 'Label', closed: false},
  {title: 'Select', closed: false},
  {title: 'Textarea', closed: true},
]

//   a, bdo, br, img, map, object, q, script, span, sub, sup
// button, input, label, select, textarea

export {tagsBlock, tagsInline};
